AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - lib/tasks/auto_annotate_models.rake
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - Gemfile
    - Guardfile
  TargetRubyVersion: 2.4
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/IfUnlessModifier:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'config.ru'
    - 'Rakefile'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2
