version: '3'

services:
  db:
    image: mysql:5.7.16
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql

  web:
    image: yamatatsu193/somethingonrails_web:latest
    ports:
      - 3010:3010
    volumes:
      - .:/myapp
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://db
    depends_on:
      - db

volumes:
  db-data:
    driver: local
